### ISSUE TITLE
Client App Issues

### ISSUE THREAD

**Issue by ryansennis** [NoahKarran/LiveSupportBETA#3]
Client is able to delete the entire text field and has no way of communicating to server

**Comment by NoahKarran** [comment]
Hmm..... that shouldn't happen. I will investigate immediately. I'll get back to you with any updates on this situation. Once again sorry!
-Noah

**Comment by NoahKarran** [comment]
The issue has been found and we are working on it.

**Comment by ryansennis** [comment]
Fixed problem with messages being deleted by user.

**Comment by ryansennis** [comment]
Everything is fixed
